
# Site settings
title: Through the sands of the hourglass, these are the data of our lives
subtitle: "FAIRing the DLI Training Repository"
#email: youremailaddress@gmail.com
#description: The Jekyll version of the Massively theme by HTML5 UP.
#baseurl: "/massively-jekyll-theme" # the subpath of your site, e.g. /blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tr-dli.github.io/" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
date_format: "%b %-d, %Y"

sass:
  sass_dir: _sass

social_links:
    twitter:
    github: dli-training
    rss: rss

include:
  - _pages
  - _posts

exclude:
  - .gitignore
  - LICENSE.txt
  - _site/
  - "*.ai"
